import {StyleSheet} from "react-native";
import colors from "../../styles/colors";

const styles = StyleSheet.create({
    container: {
        paddingTop:8,
        flex: 1,
        backgroundColor: colors.background,
    },
    section: {
        elevation:10,
        margin:4,
        borderRadius: 16,
        backgroundColor: colors.secondary,
        marginBottom: 4,
        padding: 12,
    },
    section2: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        margin:6,
        borderRadius: 16,
        backgroundColor: colors.secondary,
        marginBottom: 8,
        padding: 16,
    },
    mainTitle: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 16,
        color: colors.white,
    },
    transferGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    menuItem: {
        width: '23%',
        alignItems: 'center',
        marginBottom: 16,
    },
    iconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    menuItemText: {
        fontSize: 12,
        fontWeight: '500',
        textAlign: 'center',
        color: colors.white,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.white,
    },
    viewAllText: {
        color: colors.primary,
        fontSize: 14,
    },
    upiSection: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        marginBottom: 6,
        gap: 8,
    },
    upiLiteButton: {
        backgroundColor: colors.secondary,
        borderWidth:2,
        borderColor:colors.gray,
        padding: 8,
        borderRadius: 8,
    },
    upiLiteText: {
        fontSize:12,
        color: colors.white,
        fontWeight: '500',
    },
    upiIdButton: {
        backgroundColor: colors.secondary,
        borderWidth:2,
        borderColor:colors.gray,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 8,
        borderRadius: 8,
    },
    upiIdText: {
        fontWeight: '500',
        fontSize:12,
        color: colors.white,
    },
    quickActions: {
        elevation:10,
        backgroundColor: colors.background,
        flexDirection: 'row',
        justifyContent: 'space-between',
        margin: 8,
    },
    quickActionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.secondary,

        padding: 8,
        borderRadius: 8,
        flex: 1,
        marginHorizontal: 4,
    },
    quickActionText: {
        paddingHorizontal:10,
        fontSize: 14,
        color: colors.white,
        marginLeft: 4,
    },
    gridContainer: {
        elevation:10,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    badge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: colors.success,
        width: 16,
        height: 16,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: 'white',
        fontSize: 12,
        fontWeight: 'bold',
    },
    rewardBadge: {
        backgroundColor: colors.success,
        width: 16,
        height: 16,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: -8,
    },
    rewardBadgeText: {
        color: 'white',
        fontSize: 12,
        fontWeight: 'bold',
    },
});

export default styles;