spring.application.name=PhonePe

spring.datasource.url=jdbc:postgresql://localhost:5432/phonepe_db
spring.datasource.username=avinash
spring.datasource.password=0569
spring.datasource.driver-class-name=org.postgresql.Driver