spring.application.name=${SPRING_APPLICATION_NAME}
#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

#Logging
logging.level.root=${LOGGING_LEVEL_ROOT}
logging.level.org.springframework.kafka=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA}
logging.level.org.springframework.web=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB}
logging.level.org.hibernate=${LOGGING_LEVEL_ORG_HIBERNATE}

#Kafka
spring.kafka.consumer.bootstrap-servers=${SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
